hide_ascii      = false
spacing         = 1
padding         = 0
separator       = ">>"
key_color       = "#ea76cb"
separator_color = "#df8e1d"

[box]
title           = " Sharj "
border          = "plain"
visible         = true

[box.inner_margin]
x               = 1
y               = 1

[custom_ascii]
color           = "#04a5e5"
path = "~/.config/macchina/themes/ellen.txt"

[keys]
terminal = "Term"
packages = "Package"
