bindsym $mod+q kill
bindsym $mod+Ctrl+Shift+e exit
bindsym Ctrl+Shift+space exec $drun
bindsym $mod+Shift+e exec $powerMenu
bindsym $mod+Return exec $terminal
bindsym $mod+n exec $fileManager
bindsym $mod+p exec $screenshot
bindsym $mod+Shift+p exec $screenclip
bindsym $mod+Ctrl+Shift+p exec $winclip
bindsym Ctrl+Shift+s exec $record
bindsym $mod+v exec $clipboard
bindsym $mod+Ctrl+Shift+w exec $wayfix
bindsym $mod+Ctrl+Shift+r exec $wallswitch
bindsym $mod+Ctrl+Shift+l exec hyprlock
bindsym $mod+Ctrl+Shift+o exec swaymsg reload
bindsym $mod+Shift+d exec makoctl dismiss

bindsym $mod+h focus left
bindsym $mod+l focus right
bindsym $mod+k focus up
bindsym $mod+j focus down

bindsym $mod+Shift+h move left
bindsym $mod+Shift+l move right
bindsym $mod+Shift+k move up
bindsym $mod+Shift+j move down

bindsym $mod+f fullscreen
bindsym $mod+space floating toggle

bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

bindsym $mod+button1 move
bindsym $mod+button2 resize

bindsym $mod+equal exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindsym $mod+minus exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindsym XF86AudioMicMute exec wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindsym XF86MonBrightnessUp exec brightnessctl s 10%+
bindsym XF86MonBrightnessDown exec brightnessctl s 10%-
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPause exec playerctl play-pause
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioPrev exec playerctl previous
