$terminal = foot
$fileManager= thunar
$drun = ~/.scripts/bemenu_run
$powerMenu = ~/.scripts/bemenu_power
$screenshot = hyprshot -m active -m output
$screenclip = hyprshot -m region
$winclip = hyprshot -m active -m window
$wayfix = ~/.config/hypr/wayfix.sh
$wallswitch = ~/.config/hypr/wallswitch.sh
$clipboard = foot --title clipse -e clipse
$layout = ~/.config/waybar/layout.sh toggle
$record = ~/.scripts/record.sh
