workspace = special:gromit,on-created-empty: gromit-mpx -a

bind = Super, G, exec, gromit-mpx -a
bind = Super CTRL SHIFT , G, exec, gromit-mpx --clear
bind = Super CTRL, G, exec, gromit-mpx --undo
bind = Super SHIFT, G, exec, gromit-mpx --redo
