preload = ~/Pictures/wallpapers/miyabi1.jpg
preload = ~/Pictures/wallpapers/ellen1.jpg
wallpaper = DP-1, ~/Pictures/wallpapers/miyabi1.jpg
wallpaper = DP-2, ~/Pictures/wallpapers/ellen1.jpg
#preload = ~/Pictures/wallpapers/frieren2.jpg
#wallpaper = , ~/Pictures/wallpapers/frieren2.jpg
