set $mod Mod4
set $terminal foot
set $fileManager thunar
set $drun ~/.scripts/bemenu_run
set $powerMenu ~/.scripts/bemenu_power
set $screenshot ~/.scripts/grimshot/grimshot --notify savecopy output
set $screenclip ~/.scripts/grimshot/grimshot --notify savecopy area
set $winclip ~/.scripts/grimshot/grimshot --notify savecopy window
set $wayfix ~/.config/hypr/wayfix.sh
set $wallswitch ~/.config/hypr/wallswitch.sh
set $clipboard foot --title clipse -e clipse
set $layout ~/.config/waybar/layout.sh toggle
set $record ~/.scripts/record.sh

