gaps inner 7
gaps outer 0

default_border pixel 1
# Colors 										border  bg      text    indi    childborder
client.focused							#83a598 #83a598 #ebdbb2 #83a598 #83a598
client.focused_inactive 	#fabd2f #fabd2f #ebdbb2 #fabd2f #fabd2f
client.unfocused						#fabd2f #fabd2f #ebdbb2 #fabd2f #fabd2f
client.urgent 							#fb4934 #fb4934 #fb4934 #fb4934 #fb4934

blur enable
blur_passes 1
blur_radius 5
blur_noise 0.1
blur_saturation 1
shadows disable
default_dim_inactive 0.2

output DP-1 background ~/Pictures/wallpapers/miyabi1.jpg fill
output DP-2 background ~/Pictures/wallpapers/ellen1.jpg fill

exec_always --no-startup-id env XCURSOR_SIZE=24
