for_window [app_id="steam" title="Friends List"] floating enable
for_window [app_id="steam" title="Friends List"] resize set 300 635
for_window [app_id="foot" title="clipse"] floating enable
for_window [app_id="foot" title="clipse"] resize set 622 652
