for_window [class="steam" title="Friends List"] floating enable
for_window [class="steam" title="Friends List"] resize set 300 635
for_window [title="clipse"] floating enable
for_window [title="clipse"] resize set 622 652
